  # All sources that should be downloaded
  #
  # Parameters:
  #  download_runner_retries[default=3]: Number of times to retry the job if it fails
  #  download_runner_async[default=30]: Number of seconds to wait before checking if the job is finished
  #  download_retries[default=18]: Number of times to retry the check
  #  download_delay[default=5]: Delay in seconds between the checks
  #  unpack_async[default=30]: Number of seconds to wait before checking if the job is finished
  #  unpack_retries[default=6]: Number of times to retry the check
  #  unpack_delay[default=5]: Delay in seconds between the checks
  jobs:
    - { name: "athaliana" }
    - { name: "bar" }
    - { name: "bhf_ucl" }
    - { name: "bind" }
    # - { name: "bind_translation" }
    # - { name: "dig" }
    # - { name: "dip" }
    # - { name: "fly" }
    # - { name: "hpidb" }
    # - { name: "hprd" }
    # - { name: "innatedb" }
    # - { name: "ipi" }
    # - { name: "mbinfo" }
    # - { name: "mpact" }
    # - { name: "mpidb" }
    # - { name: "mppi" }
    # - { name: "psi_mi" }
    # - { name: "quickgo" }
    # - { name: "intact", unpack_async: 180, unpack_delay: 30 }
    # - { name: "intcomplex", unpack_async: 60, unpack_delay: 10 , download_retries: 6 }
    # - { name: "huri" , download_runner_async: 60, download_retries: 36 }
    # - { name: "pdb" , download_runner_async: 60, download_retries: 36 }
    # - { name: "mmdb" , download_runner_async: 60, download_retries: 36 }
    - { name: "taxonomy" , download_runner_async: 60, download_retries: 36 }
    # - { name: "virushost" , download_runner_async: 60, download_retries: 36 }
    # - { name: "yeast" , download_runner_async: 60, download_retries: 36 }
    # - { name: "biogrid", unpack_async: 120, unpack_retries: 8, unpack_delay: 15 , download_runner_async: 60, download_retries: 12, download_delay: 15 }
    # - { name: "corum" , download_runner_async: 60, download_retries: 12, download_delay: 15 }
    # - { name: "matrixdb" , download_runner_async: 300, download_retries: 30, download_delay: 30 }
    # - { name: "uniprotpp" , download_runner_async: 300, download_retries: 30, download_delay: 30 }
    # - { name: "uniprot" , download_runner_async: 60, download_retries: 36 }
    # - { name: "mint" , download_runner_async: 600, download_retries: 60, download_delay: 30 }
    # - { name: "gene" , download_runner_async: 600, download_retries: 60, download_delay: 30 }
    # - { name: "reactome" , download_runner_async: 300, download_retries: 30, download_delay: 30 }
    # - { name: "imex" , download_runner_async: 10800, download_retries: 108, download_delay: 300 }
    # - { name: "refseq" , download_runner_async: 36000, download_retries: 60, download_delay: 1800 }
    # - { name: "genpept" , download_runner_async: 36000, download_retries: 60, download_delay: 1800 }
