= Personal Development
// tag::assignment[]
Luc Ducazu <luc.ducazu@student.howest.be>

== Assignment

*Refinement of a reproducible pipeline for consolidated protein interaction data*

The project concerns the updating and maintaining of the iRefIndex resource, developed in the VIB lab of S. Wodak, Brussels. Currently, the VIB Bioinformatics Core is the maintainer of the database resource. The resource offers access to non-redundant data on protein-protein interactions (PPI) in over a thousand organisms (http://irefindex.vib.be/). These data are consolidated from more than 14 major public databases that curate the scientific literature using a uniquely rigorous consolidation procedure. During the project, it is envisaged to refine the current consolidation pipeline to arrive at a fully reproducible pipeline. This includes the automated build of the needed server by means of Ansible scripts on e.g. Google Cloud as well as the inclusion of more plant specific protein interaction data.
// end::assignment[]

== Learning Outcome

The intership offers the opportunity to dive into public cloud technology, which is little known territory to me.
In particular the use of virtual machines and managed SQL databases is in scope of the internship.
To automate and document the steps required to set up a (Google) cloud project, virtual machines, disks and other
cloud resources, _Terraform_ is one of the more popular tools in the Infrastructure as Code (IaC) space.

The first objective is to set up all cloud resources used during the traineeship using _Terraform_ config files.
These plain text files will be hosted in a Git repo separate from the VIB repositories:
https://source.cloud.google.com/irefindex/howest-stage/+/master:terraform/

Terraform documentation:

* Terraform https://learn.hashicorp.com/tutorials/terraform/install-cli[Installation Guide^]
* Terraform for GCP https://registry.terraform.io/providers/hashicorp/google/latest/docs[Reference^]
  / https://registry.terraform.io/browse/modules?provider=google[Module Index]
* Authentication https://cloud.google.com/docs/authentication/best-practices-applications[Best Practices^]
* GCP Tutorials: https://learn.hashicorp.com/tutorials/terraform/google-cloud-platform-build[HashiCorp^]
  / https://cloud.google.com/docs/terraform[Google^]
* https://www.oreilly.com/library/view/terraform-up/9781492046899/[Terraform: Up & Running^] (2nd Edition)
  by Yevgeniy Brikman, Released September 2019, Publisher(s): O'Reilly Media, Inc., ISBN: 9781492046905

The second objective is to configure any virtual machine using _Ansible_, a configuration management tool.
The playbooks can be found under https://source.cloud.google.com/irefindex/howest-stage/+/master:ansible/

Ansible documentation:

* Ansible Google Cloud https://docs.ansible.com/ansible/latest/scenario_guides/guide_gce.html[Platform Guide^]
* Ansible Google Cloud https://docs.ansible.com/ansible/latest/collections/google/cloud/index.html[Reference^]
* Ansible https://docs.ansible.com/ansible/latest/collections/community/postgresql/index.html[Community.Postgresql^]
* https://www.oreilly.com/library/view/ansible-up-and/9781491979792/[Ansible: Up and Running^] (2nd Edition)
  by Lorin Hochstein & Rene Moser, Released August 2017, Publisher(s): O'Reilly Media, Inc., ISBN: 9781491979808

