#!/bin/sh

if [ -e "irdata-config" ]; then
    . "$PWD/irdata-config"
elif [ -e "scripts/irdata-config" ]; then
    . 'scripts/irdata-config'
else
    . 'irdata-config'
fi

if [ "$1" = '--help' ] || [ ! "$1" ]; then
    cat 1>&2 <<EOF
Usage: $PROGNAME [ --build [ --no-download ] ] [ --reports ] [ --output ]

Build interactor and assignment information from the imported source data.
EOF
    exit 1
fi

if [ "$1" = '--build' ]; then
    BUILD=$1
    shift 1
else
    BUILD=
fi

if [ "$1" = '--no-download' ]; then
    MISSING_OPTIONS='--import'
    shift 1
else
    MISSING_OPTIONS='--all'
fi

if [ "$1" = '--reports' ]; then
    MAKE_REPORTS=$1
    shift 1
else
    MAKE_REPORTS=
fi

if [ "$1" = '--output' ]; then
    MAKE_OUTPUT=$1
    shift 1
else
    MAKE_OUTPUT=
fi

if [ "$BUILD" ]; then

    # Convert MITAB-based data to an XML-compatible representation.

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/mitab_to_xml.sql" ; then
        echo "$PROGNAME: Could not convert MITAB data to the common data representation." 1>&2
        exit 1
    fi

    # Finalise the XML-based data.

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_constraints.sql" ; then
        echo "$PROGNAME: Constraints could not be applied to the common data representation." 1>&2
        exit 1
    fi

    # Identify the interactors.

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_interactors.sql" ; then
        echo "$PROGNAME: Could not build interactor information from the imported data." 1>&2
        exit 1
    fi

    # Add missing interactor information.

    if ! "$SCRIPTS/irmissing" $MISSING_OPTIONS ; then
        echo "$PROGNAME: Did not retrieve missing/unknown sequences." 1>&2
        exit 1
    fi
fi

if [ "$MAKE_REPORTS" ]; then

    # Make an interactor report, if requested.

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$REPORTS/interactors_by_source.sql" "$DATA" ; then
        echo "$PROGNAME: Could not report source interactor information." 1>&2
        exit 1
    fi
fi

if [ "$BUILD" ]; then

    # Make canonical interactor information.

    if ! "$SCRIPTS/ircanonical" ; then
        echo "$PROGNAME: Did not make canonical information." 1>&2
        exit 1
    fi

    # Assign definitive sequence information to interactors.

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_assignments.sql" ; then
        echo "$PROGNAME: Could not build assignment information from the imported data." 1>&2
        exit 1
    fi
fi

if [ "$MAKE_REPORTS" ]; then

    # Make assigned interactor reports, if requested.

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$REPORTS/assignments_by_source.sql" "$DATA" ; then
        echo "$PROGNAME: Could not report sequence assignment information." 1>&2
        exit 1
    fi

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$REPORTS/rogids_by_source.sql" "$DATA" ; then
        echo "$PROGNAME: Could not report ROG identifier assignment information." 1>&2
        exit 1
    fi

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$REPORTS/rogids_by_score.sql" "$DATA" ; then
        echo "$PROGNAME: Could not report ROG identifier scoring information." 1>&2
        exit 1
    fi
fi

if [ "$BUILD" ]; then

    # Export ROG information for RIG identifier calculation, make and import RIG identifiers.

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/export_irefindex_rogids.sql" "$DATA" ; then
        echo "$PROGNAME: Could not export ROG identifiers for assigned sequences." 1>&2
        exit 1
    fi

    if ! "$TOOLS/irdata_process_signatures.py" "$DATA/rogids_for_interactions" "$DATA/rigids_for_interactions" ; then
        echo "$PROGNAME: Could not generate RIG identifiers for the exported ROG identifiers." 1>&2
        exit 1
    fi

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_rigids.sql" "$DATA" ; then
        echo "$PROGNAME: Could not import the generated RIG identifiers." 1>&2
        exit 1
    fi
fi

if [ "$MAKE_REPORTS" ]; then

    # Make an interactions report, if requested.

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$REPORTS/rigids_by_source.sql" "$DATA" ; then
        echo "$PROGNAME: Could not report RIG identifier assignment information." 1>&2
        exit 1
    fi

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$REPORTS/rigids_by_taxonomy.sql" "$DATA" ; then
        echo "$PROGNAME: Could not report RIG identifier taxonomy statistics." 1>&2
        exit 1
    fi

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$REPORTS/interactions_by_source.sql" "$DATA" ; then
        echo "$PROGNAME: Could not report interaction statistics." 1>&2
        exit 1
    fi

    if ! "$TOOLS/irdata_reports2wiki.py" "$DATA" "$DATA/Statistics.wiki" "$WIKIFORMAT" ; then
        echo "$PROGNAME: Could not generate statistics Wiki page." 1>&2
        exit 1
    fi
fi

if [ "$BUILD" ]; then

    # Make convenient representations for other entity types.

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_interactions.sql" ; then
        echo "$PROGNAME: Could not build interaction information from the imported data." 1>&2
        exit 1
    fi

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_experiments.sql" ; then
        echo "$PROGNAME: Could not build experiment information from the imported data." 1>&2
        exit 1
    fi

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_participants.sql" ; then
        echo "$PROGNAME: Could not build participant information from the imported data." 1>&2
        exit 1
    fi
fi

if [ "$MAKE_OUTPUT" ]; then

    # Make output files.

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/export_irefindex_mitab.sql" ; then
        echo "$PROGNAME: Could not generate MITAB data." 1>&2
        exit 1
    fi
fi
