#!/bin/sh

# Copyright (C) 2012 Ian Donaldson <ian.donaldson@biotek.uio.no>
# Original author: Paul Boddie <paul.boddie@biotek.uio.no>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ -e "irdata-config" ]; then
    . "$PWD/irdata-config"
elif [ -e "scripts/irdata-config" ]; then
    . 'scripts/irdata-config'
else
    . 'irdata-config'
fi

if [ "$1" = '--help' ] || [ "$1" != '--build' ] ; then
    cat 1>&2 <<EOF
Usage: $PROGNAME --build

Initialise the canonical interactor schema and define the canonical groups of
interactors.
EOF
    exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_canonical.sql" ; then
    echo "$PROGNAME: Could not initialise the canonical schema." 1>&2
    exit 1
fi

# Combine groups of genes until no more updates can be made.

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_canonical_iteration.sql" "$DATA" ; then
    echo "$PROGNAME: Could not update the canonical schema." 1>&2
    exit 1
fi

while [ `cat "$DATA/canonical_updates"` != '0' ]; do
    echo "$PROGNAME: Updating the canonical schema..." 1>&2

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_canonical_iteration.sql" "$DATA" ; then
        echo "$PROGNAME: Could not update the canonical schema." 1>&2
        exit 1
    fi

done

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_canonical_final.sql" ; then
    echo "$PROGNAME: Could not define the canonical representative interactors." 1>&2
    exit 1
fi
