#!/bin/sh

if [ -e "irdata-config" ]; then
    . 'irdata-config'
elif [ -e "scripts/irdata-config" ]; then
    . 'scripts/irdata-config'
else
    . 'irdata-config'
fi

if [ "$1" == '--help' ]; then
    cat 1>&2 <<EOF
Usage: $PROGNAME [ --check ] ( --all | <source>... )

Download data from the different sources, or if the --check option is specified
check whether a download needs to be performed. The sources are configured to be
the following when --all is specified:

$ALLSOURCES
EOF
    exit 1
fi

if [ "$1" == '--check' ]; then
    CHECK_ONLY=$1
    shift 1
fi

SOURCES=$1

if [ "$SOURCES" == '--all' ]; then
    SOURCES=$ALLSOURCES
elif [ ! "$SOURCES" ]; then
    echo "$PROGNAME: No sources specified." 1>&2
    exit 1
fi

# Download data.

for SOURCE in $SOURCES; do
    eval RELEASE_URL='$'"$SOURCE"_RELEASE_URL
    eval DOWNLOAD_FILES='$'"$SOURCE"_DOWNLOAD_FILES
    eval SOURCEDIR='$'"$SOURCE"_DIR_NAME

    DATADIR="$DATA/$SOURCEDIR"

    if [ "$CHECK_ONLY" ]; then
        echo "$PROGNAME: Checking $SOURCE..." 1>&2
    else
        echo "$PROGNAME: Downloading $SOURCE..." 1>&2
        if [ ! -e "$DATADIR" ]; then
            mkdir "$DATADIR"
        fi
    fi

    for DOWNLOAD in $DOWNLOAD_FILES; do
        DOWNLOADED="$DATADIR/$DOWNLOAD"

        if [ ! -e "$DOWNLOADED" ]; then
            if [ "$CHECK_ONLY" ]; then
                echo "$PROGNAME: Want to download file: $DOWNLOAD" 1>&2
            else
                echo "$PROGNAME: Downloading file: $DOWNLOAD" 1>&2
                wget -O "$DOWNLOADED" "${RELEASE_URL}$DOWNLOAD"
                echo "$DOWNLOADED"
            fi
        fi
    done
done
