#!/bin/sh

# Copyright (C) 2012 Ian Donaldson <ian.donaldson@biotek.uio.no>
# Original author: Paul Boddie <paul.boddie@biotek.uio.no>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ -e "irdata-config" ]; then
    . "$PWD/irdata-config"
elif [ -e "scripts/irdata-config" ]; then
    . 'scripts/irdata-config'
else
    . 'irdata-config'
fi

if [ "$1" = '--help' ] || [ "$1" != '--drop' ]; then
    cat 1>&2 <<EOF
Usage: $PROGNAME --drop ( --all | --build ) [ -f ]

Remove schema definitions from the database.
EOF
    exit 1
fi

shift 1

if [ "$1" = '--all' ]; then
    DROPALL=$1
elif [ "$1" = '--build' ]; then
    DROPBUILD=$1
else
    echo "$PROGNAME: Either --all or --build must be given." 1>&2
    exit 1
fi

shift 1

if [ "$1" = '-f' ]; then
    FORCE=$1
fi

# If requested, drop all source data tables.

if [ "$DROPALL" ]; then

    if ! ( "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop.sql" $PSQL_OPTIONS \
        && "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_psixml.sql" $PSQL_OPTIONS \
        && "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_mitab.sql" $PSQL_OPTIONS \
        ) ; then
        echo "$PROGNAME: Could not remove the database schema." 1>&2
        exit 1
    fi

    # Remove any special schemas for data sources.

    for SOURCE in $ALLSOURCES ; do
        eval SCHEMA='$'"$SOURCE"_SCHEMA

        if [ "$SCHEMA" ]; then
            if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_${SCHEMA}.sql" $PSQL_OPTIONS ; then
                echo "$PROGNAME: Could not remove schema for $SOURCE." 1>&2
                exit 1
            fi
        fi
    done
fi

# Remove the different build tables.
# Continue without exiting if the force option is given.

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_manifest.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not remove the manifest schema." 1>&2
    [ ! "$FORCE" ] && exit 1
fi

if [ ! "$DROPALL" ] && ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_constraints.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not remove the common representation's constraints." 1>&2
    [ ! "$FORCE" ] && exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_sequences.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not remove the consolidated sequence information schema." 1>&2
    [ ! "$FORCE" ] && exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_archived.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not remove the archived sequence information schema." 1>&2
    [ ! "$FORCE" ] && exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_interactors.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not remove the interactor information schema." 1>&2
    [ ! "$FORCE" ] && exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_gene_mappings.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not remove the gene-to-protein mappings schema." 1>&2
    [ ! "$FORCE" ] && exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_canonical.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not remove the canonical interactor information schema." 1>&2
    [ ! "$FORCE" ] && exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_assignments.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not remove the assignment information schema." 1>&2
    [ ! "$FORCE" ] && exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_rigids.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not remove the interaction information schema." 1>&2
    [ ! "$FORCE" ] && exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_integer_identifiers.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not remove the integer identifier mappings schema." 1>&2
    [ ! "$FORCE" ] && exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_interactions.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not remove the additional interaction information schema." 1>&2
    [ ! "$FORCE" ] && exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_experiments.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not remove the additional experiment information schema." 1>&2
    [ ! "$FORCE" ] && exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_participants.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not remove the additional participant information schema." 1>&2
    [ ! "$FORCE" ] && exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_confidence.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not remove the confidence score schema." 1>&2
    [ ! "$FORCE" ] && exit 1
fi
