#!/usr/bin/env python

"""
Print the last modified time of each of the given filenames.

--------

Copyright (C) 2012 Ian Donaldson <ian.donaldson@biotek.uio.no>
Original author: Paul Boddie <paul.boddie@biotek.uio.no>

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from os.path import getmtime, split
from time import gmtime, strftime
import sys

progname = split(sys.argv[0])[-1]

if len(sys.argv) < 2:
    print >>sys.stderr, "%s: At least one filename is required." % progname
    sys.exit(1)

try:
    for filename in sys.argv[1:]:
        print strftime("%Y-%m-%d %H:%M:%S", gmtime(getmtime(filename)))
except OSError, exc:
    print >>sys.stderr, "%s: %s" % (progname, exc)
    sys.exit(1)

# vim: tabstop=4 expandtab shiftwidth=4
