#!/usr/bin/env python

"""
Print the last modified time of each of the given filenames.
"""

from os.path import getmtime, split
from time import gmtime, strftime
import sys

progname = split(sys.argv[0])[-1]

if len(sys.argv) < 2:
    print >>sys.stderr, "%s: At least one filename is required." % progname
    sys.exit(1)

try:
    for filename in sys.argv[1:]:
        print strftime("%Y-%m-%d %H:%M:%S", gmtime(getmtime(filename)))
except OSError, exc:
    print >>sys.stderr, "%s: %s" % (progname, exc)
    sys.exit(1)

# vim: tabstop=4 expandtab shiftwidth=4
