#!/bin/sh

# Copyright (C) 2012 Ian Donaldson <ian.donaldson@biotek.uio.no>
# Original author: Paul Boddie <paul.boddie@biotek.uio.no>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ -e "irdata-config" ]; then
    . "$PWD/irdata-config"
elif [ -e "scripts/irdata-config" ]; then
    . 'scripts/irdata-config'
else
    . 'irdata-config'
fi

if [ "$1" = '--help' ] || [ "$1" != '--init' ]; then
    cat 1>&2 <<EOF
Usage: $PROGNAME --init

Initialise the system for import and build.
EOF
    exit 1
fi

if ! ( "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init.sql" $PSQL_OPTIONS \
    && "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_psixml.sql" $PSQL_OPTIONS \
    && "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_mitab.sql" $PSQL_OPTIONS \
    && "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_manifest.sql" $PSQL_OPTIONS \
    ) ; then
    echo "$PROGNAME: Could not initialise the database schema." 1>&2
    exit 1
fi

# Initialise any special schemas for data sources.

for SOURCE in $ALLSOURCES ; do
    eval SCHEMA='$'"$SOURCE"_SCHEMA

    if [ "$SCHEMA" ]; then
        if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_${SCHEMA}.sql" $PSQL_OPTIONS ; then
            echo "$PROGNAME: Could not initialise schema for $SOURCE." 1>&2
            exit 1
        fi
    fi
done

# Initialise the different build tables.

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_sequences.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not initialise the consolidated sequence information schema." 1>&2
    exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_archived.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not initialise the archived sequence information schema." 1>&2
    exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_interactors.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not initialise the interactor information schema." 1>&2
    exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_gene_mappings.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not initialise the gene-to-protein mappings schema." 1>&2
    exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_canonical.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not initialise the canonical interactor information schema." 1>&2
    exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_assignments.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not initialise the assignment information schema." 1>&2
    exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_rigids.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not initialise the interaction information schema." 1>&2
    exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_integer_identifiers.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not initialise the integer identifier mappings schema." 1>&2
    exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_interactions.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not initialise the additional interaction information schema." 1>&2
    exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_experiments.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not initialise the additional experiment information schema." 1>&2
    exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_participants.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not initialise the additional participant information schema." 1>&2
    exit 1
fi

if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_confidence.sql" $PSQL_OPTIONS ; then
    echo "$PROGNAME: Could not initialise the confidence score schema." 1>&2
    exit 1
fi
