#!/bin/sh

if [ -e "irdata-config" ]; then
    . "$PWD/irdata-config"
elif [ -e "scripts/irdata-config" ]; then
    . 'scripts/irdata-config'
else
    . 'irdata-config'
fi

if [ "$1" = '--help' ]; then
    cat 1>&2 <<EOF
Usage: $PROGNAME --check | --download | --import | --all

Obtain missing data by exporting identifiers that do not correspond to sequence
information and using the list of identifiers to retrieve available records in
an activity separate from the original download activities.
EOF
    exit 1
fi

if [ "$1" = '--check' ] || [ "$1" = '--all' ] ; then
    CHECK=$1
    shift 1
fi

if [ "$1" = '--download' ] || [ "$1" = '--all' ] ; then
    DOWNLOAD=$1
    shift 1
fi

if [ "$1" = '--import' ] || [ "$1" = '--all' ] ; then
    IMPORT=$1
    shift 1
fi

if [ ! "$CHECK" ] && [ ! "$DOWNLOAD" ] && [ ! "$IMPORT" ]; then
    echo "$PROGNAME: Need to specify an operation or --all." 1>&2
    exit 1
fi

DATADIR="$DATA/import/RefSeq.unknown"

if [ ! -e "$DATADIR" ] ; then
    mkdir "$DATADIR"
fi

if [ "$CHECK" ] ; then
    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/export_unknown_refseq.sql" "$DATADIR" ; then
        echo "$PROGNAME: Could not export RefSeq identifiers not providing sequences." 1>&2
        exit 1
    fi

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/export_unknown_gi.sql" "$DATADIR" ; then
        echo "$PROGNAME: Could not export GenBank identifiers not providing sequences." 1>&2
        exit 1
    fi

    # Combine the unknown identifiers.

    cat "$DATADIR/unknown_refseq" "$DATADIR/unknown_gi" > "$DATADIR/unknown_all"
    RESULT="$DATADIR/unknown_all"
fi

if [ "$DOWNLOAD" ] ; then
    if ! "$TOOLS/irdata_fetch_refseq.sh" "$DATADIR" "$DATADIR/unknown_all" ; then
        echo "$PROGNAME: No RefSeq sequence records downloaded." 1>&2
        exit 1
    fi

    RESULT="$DATADIR/unknown_all.result"
fi

if [ "$IMPORT" ] ; then
    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_unknown_refseq.sql" "$DATADIR" ; then
        echo "$PROGNAME: Could not import missing sequences." 1>&2
        exit 1
    fi

    RESULT=
fi

echo $RESULT
