#!/bin/sh

# Copyright (C) 2012 Ian Donaldson <ian.donaldson@biotek.uio.no>
# Original author: Paul Boddie <paul.boddie@biotek.uio.no>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ -e "irdata-config" ]; then
    . "$PWD/irdata-config"
elif [ -e "scripts/irdata-config" ]; then
    . 'scripts/irdata-config'
else
    . 'irdata-config'
fi

if [ "$1" = '--help' ] || [ ! "$1" ]; then
    cat 1>&2 <<EOF
Usage: $PROGNAME --pgsql <database> | --mysql <option>...

Export integer identifiers from a previous release of iRefIndex.
EOF
    exit 1
fi

if [ "$1" = '--pgsql' ]; then
    PGSQL=$1
    DATABASE=$2

    if [ ! "$DATABASE" ]; then
        echo "$PROGNAME: A specific database must be specified." 1>&2
        exit 1
    fi

elif [ "$1" = '--mysql' ]; then
    MYSQL=$1
    shift 1
    OPTIONS=$*

else
    echo "$PROGNAME: A database system option must be specified." 1>&2
    exit 1
fi

if [ "$PGSQL" ]; then

    # Export identifiers from a PostgreSQL database.

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/export_irefindex_integer_rigids.sql" "$DATA" ; then
        echo "$PROGNAME: Could not export integer RIG identifiers from the previous database." 1>&2
        exit 1
    fi

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/export_irefindex_integer_rogids.sql" "$DATA" ; then
        echo "$PROGNAME: Could not export integer ROG identifiers from the previous database." 1>&2
        exit 1
    fi

    # Export archived identifiers from a PostgreSQL database.

    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/export_irefindex_archived.sql" "$DATA" ; then
        echo "$PROGNAME: Could not export archived identifiers from the previous database." 1>&2
        exit 1
    fi

elif [ "$MYSQL" ]; then

    # Export identifiers from a MySQL database.

    if ! mysql -N $OPTIONS < "$SQL/mysql/export_irefindex_integer_rigids.sql" > "$DATA/rig2rigid" ; then
        echo "$PROGNAME: Could not export integer RIG identifiers from the previous database." 1>&2
        exit 1
    fi

    if ! mysql -N $OPTIONS < "$SQL/mysql/export_irefindex_integer_rogids.sql" > "$DATA/rog2rogid" ; then
        echo "$PROGNAME: Could not export integer ROG identifiers from the previous database." 1>&2
        exit 1
    fi

    # Export archived identifiers from a MySQL database.

    if ! mysql -N $OPTIONS < "$SQL/mysql/export_irefindex_archived.sql" > "$DATA/sequences_archived" ; then
        echo "$PROGNAME: Could not export archived identifiers from the previous database." 1>&2
        exit 1
    fi
fi
