---
- name: Irmanifest
  hosts: localhost
  become: true
  gather_facts: true # WE NEED THIS HERE FOR THE DATES FOR THE LOGS!
  vars_files:
    - ./vars/logs.yml
    - ./vars/sources.yml

  vars:
    log_location: "{{ logs_dir }}/irmanifest"

  tasks:
    - name: Run irmanifest for each source
      ansible.builtin.command: "./irmanifest {{ item.name | upper }}"
      args:
        chdir: "/home/irefindex/usr/bin"
      changed_when: false
      register: job_result
      loop: "{{ jobs }}"

    - name: Fail jobs where conditions are met
      ansible.builtin.fail:
        msg: "FAILED: Cannot statx or grep a certain file or directory"
      when: "'stat: cannot statx' in item.stderr or 'grep' in item.stdout"
      failed_when: false
      no_log: true
      register: failed_jobs
      loop: "{{ job_result.results }}"

    - name: "Ensure that `log_location` exists"
      ansible.builtin.file:
        path: "{{ log_location }}"
        state: directory
        mode: "0755"

    - name: Copy msg
      ansible.builtin.copy:
        content: "{{ item.msg }}"
        dest: "{{ log_location }}/{{ item.item.name }}.msg"
        mode: "0644"
        remote_src: false
      no_log: true
      when: item.msg is defined and item.msg != ""
      loop: "{{ job_result.results }}"

    - name: Copy logs
      ansible.builtin.copy:
        content: "{{ item.stdout }}"
        dest: "{{ log_location }}/{{ item.item.name }}.out"
        mode: "0644"
        remote_src: false
      no_log: true
      when: item.stdout != ""
      loop: "{{ job_result.results }}"

    - name: Copy error logs
      ansible.builtin.copy:
        content: "{{ item.stderr }}"
        dest: "{{ log_location }}/{{ item.item.name }}.err"
        mode: "0644"
        remote_src: false
      no_log: true
      when: item.stderr != ""
      loop: "{{ job_result.results }}"

    - name: Gather failed jobs
      ansible.builtin.set_fact:
        filtered_failed_jobs: "{{ failed_jobs.results
                                | selectattr('msg', 'defined')
                                | selectattr('msg', 'equalto', 'Failed')
                                | list }} "
      when:
        - failed_jobs is defined
        - failed_jobs.results is defined

    - name: Print failed jobs
      ansible.builtin.fail:
        msg: >-
          The following resources failed to unpack: {{
          filtered_failed_jobs
          | map(attribute='item.item.name')
          | join(', ')
          }}.
          Please check the logs in `{{ log_location }}` for more information.
      when: filtered_failed_jobs is defined and filtered_failed_jobs | length > 0
