---
- name: Irmanifest
  hosts: localhost
  become: yes

  tasks:
    - name: Create file of acquired resources BIND_TRANSLATION
      command: "./irmanifest BIND_TRANSLATION"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: bind_translation_result

    - name: Fail the task when conditions are met (BIND_TRANSLATION)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in bind_translation_result.stderr or 'grep' in bind_translation_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources BIOGRID
      command: "./irmanifest BIOGRID"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: biogrid_result

    - name: Fail the task when conditions are met (BIOGRID)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in biogrid_result.stderr or 'grep' in biogrid_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources CORUM
      command: "./irmanifest CORUM"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: corum_result
      # FAILED - IRDOWNLOAD

    - name: Fail the task when conditions are met (CORUM)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in corum_result.stderr or 'grep' in corum_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources DIP
      command: "./irmanifest DIP"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: dip_result

    - name: Fail the task when conditions are met (DIP)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in dip_result.stderr or 'grep' in dip_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources HPRD
      command: "./irmanifest HPRD"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: hrpd_result

    - name: Fail the task when conditions are met (HRPD)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in hrpd_result.stderr or 'grep' in hrpd_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources INTACT
      command: "./irmanifest INTACT"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: intact_result

    - name: Fail the task when conditions are met (INTACT)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in intact_result.stderr or 'grep' in intact_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources INTCOMPLEX
      command: "./irmanifest INTCOMPLEX"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: intcomplex_result

    - name: Fail the task when conditions are met (INTCOMPLEX)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in intcomplex_result.stderr or 'grep' in intcomplex_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources MPACT
      command: "./irmanifest MPACT"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: mpact_result

    - name: Fail the task when conditions are met (MPACT)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in mpact_result.stderr or 'grep' in mpact_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources MPPI
      command: "./irmanifest MPPI"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: mppi_result

    - name: Fail the task when conditions are met (MPPI)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in mppi_result.stderr or 'grep' in mppi_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources BAR
      command: "./irmanifest BAR"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: bar_result
      # FAILED - IRDOWNLOAD

    - name: Fail the task when conditions are met (BAR)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in bar_result.stderr or 'grep' in bar_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources BHF_UCL
      command: "./irmanifest BHF_UCL"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: bhf_ucl_result

    - name: Fail the task when conditions are met (BHF_UCL)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in bhf_ucl_result.stderr or 'grep' in bhf_ucl_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources HPIDB
      command: "./irmanifest HPIDB"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: hpidb_result

    - name: Fail the task when conditions are met (HPIDB)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in hpidb_result.stderr or 'grep' in hpidb_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources HURI
      command: "./irmanifest HURI"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: huri_result

    - name: Fail the task when conditions are met (HURI)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in huri_result.stderr or 'grep' in huri_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources IMEX
      command: "./irmanifest IMEX"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: imex_result

    - name: Fail the task when conditions are met (IMEX)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in imex_result.stderr or 'grep' in imex_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources INNATEDB
      command: "./irmanifest INNATEDB"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: innatedb_result
      # FAILED - IRDOWNLOAD

    - name: Fail the task when conditions are met (INNATEDB)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in innatedb_result.stderr or 'grep' in innatedb_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources MATRIXDB
      command: "./irmanifest MATRIXDB"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: matrixdb_result

    - name: Fail the task when conditions are met (MATRIXDB)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in matrixdb_result.stderr or 'grep' in matrixdb_result.stdout"
      ignore_errors: true

    - name: Rename mbinfo_psicquic.txt.original
      command: mv /home/irefindex/var/lib/irdata/data/MBINFO/mbinfo_psicquic.txt.original /home/irefindex/var/lib/irdata/data/MBINFO/mbinfo_psicquic.txt
      args:
        creates: /home/irefindex/var/lib/irdata/data/MBINFO/mbinfo_psicquic.txt

    - name: Create file of acquired resources MBINFO
      command: "./irmanifest MBINFO"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: mbinfo_result
      # FAILED - STRANGE

    - name: Fail the task when conditions are met (MBINFO)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in mbinfo_result.stderr or 'grep' in mbinfo_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources MINT
      command: "./irmanifest MINT"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: mint_result

    - name: Fail the task when conditions are met (MINT)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in mint_result.stderr or 'grep' in mint_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources MPIDB
      command: "./irmanifest MPIDB"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: mpidb_result
      # FAILED - STRANGE

    - name: Fail the task when conditions are met (MPIDB)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in mpidb_result.stderr or 'grep' in mpidb_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources QUICKGO
      command: "./irmanifest QUICKGO"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: quickgo_result
      # FAILED - STRANGE

    - name: Fail the task when conditions are met (QUICKGO)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in quickgo_result.stderr or 'grep' in quickgo_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources REACTOME
      command: "./irmanifest REACTOME"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: reactome_result

    - name: Fail the task when conditions are met (REACTOME)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in reactome_result.stderr or 'grep' in reactome_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources UNIPROTPP
      command: "./irmanifest UNIPROTPP"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: uniprotpp_result

    - name: Fail the task when conditions are met (UNIPROTPP)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in uniprotpp_result.stderr or 'grep' in uniprotpp_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources VIRUSHOST
      command: "./irmanifest VIRUSHOST"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: virushost_result

    - name: Fail the task when conditions are met (VIRUSHOST)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in virushost_result.stderr or 'grep' in virushost_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources PSI_MI
      command: "./irmanifest PSI_MI"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: psi_mi_result

    - name: Fail the task when conditions are met (PSI_MI)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in psi_mi_result.stderr or 'grep' in psi_mi_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources TAXONOMY
      command: "./irmanifest TAXONOMY"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: taxonomy_result

    - name: Fail the task when conditions are met (TAXONOMY)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in taxonomy_result.stderr or 'grep' in taxonomy_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources ATHALIANA
      command: "./irmanifest ATHALIANA"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: athaliana_result

    - name: Fail the task when conditions are met (ATHALIANA)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in athaliana_result.stderr or 'grep' in athaliana_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources BIND
      command: "./irmanifest BIND"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: bind_result

    - name: Fail the task when conditions are met (BIND)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in bind_result.stderr or 'grep' in bind_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources DIG
      command: "./irmanifest DIG"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: dig_result

    - name: Fail the task when conditions are met (DIG)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in dig_result.stderr or 'grep' in dig_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources FLY
      command: "./irmanifest FLY"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: fly_result

    - name: Fail the task when conditions are met (FLY)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in fly_result.stderr or 'grep' in fly_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources GENE
      command: "./irmanifest GENE"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: gene_result

    - name: Fail the task when conditions are met (GENE)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in gene_result.stderr or 'grep' in gene_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources GENPEPT
      command: "./irmanifest GENPEPT"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: genpept_result

    - name: Fail the task when conditions are met (GENPEPT)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in genpept_result.stderr or 'grep' in genpept_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources IPI
      command: "./irmanifest IPI"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: ipi_result
      # FAILED - IRDOWNLOAD

    - name: Fail the task when conditions are met (IPI)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in ipi_result.stderr or 'grep' in ipi_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources MMDB
      command: "./irmanifest MMDB"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: mmdb_result

    - name: Fail the task when conditions are met (MMDB)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in mmdb_result.stderr or 'grep' in mmdb_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources PDB
      command: "./irmanifest PDB"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: pdb_result

    - name: Fail the task when conditions are met (PDB)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in pdb_result.stderr or 'grep' in pdb_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources REFSEQ
      command: "./irmanifest REFSEQ"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: refseq_result

    - name: Fail the task when conditions are met (REFSEQ)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in refseq_result.stderr or 'grep' in refseq_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources UNIPROT
      command: "./irmanifest UNIPROT"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: uniprot_result

    - name: Fail the task when conditions are met (UNIPROT)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in uniprot_result.stderr or 'grep' in uniprot_result.stdout"
      ignore_errors: true

    - name: Create file of acquired resources YEAST
      command: "./irmanifest YEAST"
      args:
        chdir: "/home/irefindex/usr/bin"
      register: yeast_result

    - name: Fail the task when conditions are met (YEAST)
      fail:
        msg: "Failed"
      when: "'stat: cannot statx' in yeast_result.stderr or 'grep' in yeast_result.stdout"
      ignore_errors: true

    - name: Ensure that /data/irdata/logs/irmanifest/ exists
      file:
        path: "/data/irdata/logs/irmanifest/"
        state: directory
        mode: 0755

    - name: Copy log files
      async_status:
        jid: "{{ item.ansible_job_id }}"
      copy:
        content: "{{ item.stdout }}"
        dest: "/data/irdata/logs/irmanifest/{{ item.name }}.log"
      loop:
        - bind_translation_result
        - biogrid_result
        - corum_result
        - dip_result
        - hprd_result
        - intact_result
        - intcomplex_result
        - mpact_result
        - mppi_result
        - bar_result
        - bhf_ucl_result
        - hpidb_result
        - huri_result
        - imex_result
        - innatedb_result
        - matrixdb_result
        - mbinfo_result
        - mint_result
        - mpidb_result
        - quickgo_result
        - reactome_result
        - uniprotpp_result
        - virushost_result
        - psi_mi_result
        - taxonomy_result
        - athaliana_result
        - bind_result
        - dig_result
        - fly_result
        - gene_result
        - genpept_result
        - ipi_result
        - mmdb_result
        - pdb_result
        - refseq_result
        - uniprot_result
        - yeast_result

    - name: Copy error log files
      async_status:
        jid: "{{ item.ansible_job_id }}"
      copy:
        content: "{{ item.stderr }}"
        dest: "/data/irdata/logs/irmanifest/{{ item.name }}.err.log"
      loop:
        - bind_translation_result
        - biogrid_result
        - corum_result
        - dip_result
        - hprd_result
        - intact_result
        - intcomplex_result
        - mpact_result
        - mppi_result
        - bar_result
        - bhf_ucl_result
        - hpidb_result
        - huri_result
        - imex_result
        - innatedb_result
        - matrixdb_result
        - mbinfo_result
        - mint_result
        - mpidb_result
        - quickgo_result
        - reactome_result
        - uniprotpp_result
        - virushost_result
        - psi_mi_result
        - taxonomy_result
        - athaliana_result
        - bind_result
        - dig_result
        - fly_result
        - gene_result
        - genpept_result
        - ipi_result
        - mmdb_result
        - pdb_result
        - refseq_result
        - uniprot_result
        - yeast_result
